config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

   root 'reports#index'

    get 'get_departments' => 'home#get_list_departments'
    get 'get_departments_list' => 'reports#get_departments_list'
    get 'get_courses_list' => 'reports#get_courses_list'
    

  resources :reports do
    member do
      get 'submit_report'
    end
  end

end

app/models/college.rb
class College < ActiveRecord::Base
has_many :reports
end

app/models/course.rb
class Course < ActiveRecord::Base
has_many :reports
end

app/models/department.rb
class Department < ActiveRecord::Base
has_many :reports
end

app/models/report.rb
class Report < ActiveRecord::Base
belongs_to :college
belongs_to :department
belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :charge_xor_payment

  private

    def charge_xor_payment
      if role_type == 'Director'
        if college_id.blank?
        errors.add(:base, "Please select college and Department!")
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_role
    User.where('id=?',current_user.id).first.role_type if current_user
  end
  helper_method :user_role
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_action :authenticate_user!, :only => [:index]
 def index
 end

 def get_list_departments
  @departments = Department.where('college_id=?',params[:college_id])
  p '##'
  p @departments
 end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :submit_report]
  before_action :authenticate_user!
  before_filter :require_permission, only: [:new,:create]

  # GET /reports
  # GET /reports.json
  def index
    if current_user.role_type == 'Advisor'
      @reports = Report.where('user_id=?',current_user.id).order('updated_at DESC')
    elsif current_user.role_type == 'Director'
      @reports = Report.where('college_id =? AND department_id=? AND status=?',current_user.college_id,current_user.department_id,'Submitted').order('updated_at DESC')
    else
      @reports = Report.all.order('updated_at DESC')
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
   @departments = @report.college_id.present? ? Department.where('college_id=?',@report.college_id) : []
   @courses = @report.department_id.present? ? Course.where('department_id=?',@report.department_id) : []
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.status = params[:report].any?{|k,v| v.empty?} ? 'Incomplete' : 'Completed'
    @report.user_id = current_user.id
    
    respond_to do |format|
      if @report.save
        format.html { redirect_to reports_url, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
     @report.status = params[:report].any?{|k,v| v.empty?} ? 'Incomplete' : 'Completed'
      if @report.update(report_params)
        format.html { redirect_to reports_url, notice: 'Report was successfully saved.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_departments_list
  @departments = Department.where('college_id=?',params[:college_id])
  @department_id = @departments.first.id
  @courses = Course.where('department_id=?',@department_id)
  end

  def get_courses_list
    @courses = Course.where('department_id=?',params[:department_id])
  end

  def submit_report
   @report.update_attributes(:status=>'Submitted')
   respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully Submitted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:college_id, :department_id, :course_id, :assessment_start_period, :assessment_end_period, :submitted_date, :status, :student_learning_utcomes, :unm_learning_goals, :unm_strategic_plan, :assessment_measures, :performance_benchmark, :data_results, :data_analysis, :recommendations, :user_id, :met_details)
    end



def require_permission
  if user_role != 'Advisor'
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "You can't create reports." }
    end
  else
   	return true
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/home/get_list_departments.js.erb
$('#department_department_id').html("<%= escape_javascript options_from_collection_for_select(@departments, :id, :name) %>");

app/views/home/index.html.erb
<h2> Coming Soon with Report Assetment Submission</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Administrative</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Administration Portal</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><%= user_role %></a></li>
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
            <li></li>
          </ul>
          
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      
       <%= yield %>      
    </div>



</body>
</html>

app/views/reports/_form.html.erb
<br><%= form_for(@report, :html => {:class=>"form-horizontal table-bordered"}) do |f| %><br>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
      <span class="col-md-2 control-label">Metadata</span>
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-1 control-label">Colleges</label>
          <div class="col-md-2">
            <%= f.collection_select :college_id, College.all, :id, :name, {:prompt => 'Select', :selected => @report.college_id},:class=>'form-control' %>
          </div>
    <label class="col-md-2 control-label">Departments</label>
    <div class="col-md-3">
      <% if action_name == 'edit' %>
        <%= f.collection_select :department_id, @departments, :id, :name, {:prompt => 'Select College First', :selected => @report.department_id},:class=>'form-control' %>
      <% else %>
        <%= f.collection_select :department_id, [], :id, :name, {:prompt => 'Please Select College First', :selected => @report.department_id},:class=>'form-control' %>
      <% end %>
    </div>
     <label class="col-md-1 control-label">Courses</label>
    <div class="col-md-3">
      <% if action_name == 'edit' %>
        <% if !@report.course_id.nil? %>
          <%= f.collection_select :course_id, @courses, :id, :name, {:selected => @report.course_id},:class=>'form-control' %>
        <%else %>
          <%= f.collection_select :course_id, [], :id, :name, {:prompt => 'Select Department First'},:class=>'form-control' %>
        <%end %>
      <% else %>
        <%= f.collection_select :course_id, [], :id, :name, {:prompt => 'Select Department First'},:class=>'form-control' %>
      <% end %>
    </div>
          </div>
      </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Assessment Period</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Start</label>
        <div class="col-md-3">
          <%= f.text_field :assessment_start_period, :id => 'start_date',:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">End</label>
        <div class="col-md-3">
          <%= f.text_field :assessment_end_period, :id => 'end_date',:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">UNM</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Learning Goals</label>
        <div class="col-md-3">
          <%= f.text_field :unm_learning_goals,:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">Strategic Plan</label>
        <div class="col-md-3">
          <%= f.text_field :unm_strategic_plan,:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Assessment</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Measures</label>
        <div class="col-md-3">
          <%= f.text_field :assessment_measures,:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">Benchmark</label>
        <div class="col-md-3">
          <%= f.text_field :performance_benchmark,:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Data</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Analysis</label>
        <div class="col-md-3">
          <%= f.text_field :data_analysis,:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">Results</label>
        <div class="col-md-3">
          <%= f.text_field :data_results,:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>
 
  <div class="form-group">
    <span class="col-md-2 control-label">Learning Outcome</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.text_area :student_learning_utcomes,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Recommendations</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.text_area :recommendations,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>
 
  <div class="form-group">
    <span class="col-md-2 control-label">Meeting Details</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.text_area :met_details,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>
 
  <div class="form-group">
    <span class="col-md-2 control-label"></span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.submit 'Save', :class=>'btn btn-primary' %>  
          <%= link_to 'Submit', submit_report_report_path(:id=>@report.id), data: { confirm: 'Are you sure want to submit to director?' }, :class=>'btn btn-primary' if @report.status=='Completed' && user_role == 'Advisor' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  $("#start_date").datepicker();
  $("#end_date").datepicker();

$( "#report_college_id" ).change(function() {
var college = $(this).val();
$.ajax({
        url: '/get_departments_list',
        data: { college_id: college}
    }); 
});

$( "#report_department_id" ).change(function() {
var department = $(this).val();
$.ajax({
        url: '/get_courses_list',
        data: { department_id: department}
    }); 
});

</script>

app/views/reports/edit.html.erb
<h2>Editing Report</h2>

<%= render 'form' %>

app/views/reports/get_courses_list.js.erb
$('#report_course_id').html("<%= escape_javascript options_from_collection_for_select(@courses, :id, :name) %>");

app/views/reports/get_departments_list.js.erb
$('#report_department_id').html("<%= escape_javascript options_from_collection_for_select(@departments, :id, :name) %>");
$('#report_course_id').html("<%= escape_javascript options_from_collection_for_select(@courses, :id, :name) %>");

app/views/reports/index.html.erb
<br>
<p id="notice"><%= notice %></p>

<%= link_to 'Create New Report', new_report_path, :class=>'btn btn-primary' if user_role == 'Advisor'%>
<% if @reports.blank? %>
 <%if user_role =="Advisor"%>
  <center><h4>You have not yet created any Reports.</h4></center>
 <% elsif user_role =="Director" %>
  <center><h4>You don't have any Reports.</h4></center>
 <%else %>
  <center><h4>No reports were created.</h4></center>
 <%end%>

<% else %>
<br><br>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <% if ['Director','Admin'].include?(user_role) %>
        <th>User</th>
      <%else%>
        <th>College</th>
        <th>Department</th>
      <%end%>
      <th>Course</th>
      <th>Start period</th>
      <th>End period</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        
        <% if ['Director','Admin'].include?(user_role) %>
          <td><%= User.where('id=?',report.user_id).first.email %></td>
        <% else %>
          <td><%= report.college_id.present? ? report.college.try(:name) : '--' %></td>
          <td><%= report.department_id.present? ? report.department.try(:name) : '--' %></td>
        <% end %>
        <td><%= report.course_id.present? ? report.course.try(:name) : '--' %></td>
        <td><%= report.assessment_start_period %></td>
        <td><%= report.assessment_end_period %></td>
        <td><%= report.status %></td>
        <td><%= link_to 'View', report, :class=>'btn btn-primary btn-xs' %></td>
        <% if report.status != 'Submitted'%>
          <td><%= link_to 'Edit', edit_report_path(report), :class=>'btn btn-primary btn-xs' %></td>
        <% end %>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-xs' %></td>
        <% if report.status == 'Completed' %>
          <td>
            <%= link_to 'Submit', submit_report_report_path(:id=>report.id), data: { confirm: 'Are you sure want to submit to director?' }, :class=>'btn btn-primary btn-xs' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

app/views/reports/new.html.erb
<br>
<center><p>Administrative Units Assessment Report Template, 
Record for Assessment of Outcomes,
The University of New Mexico</p></center>

<%= render 'form' %>

app/views/reports/show.html.erb
<br>
<ceter>
<div>
  <div class="form-group">
      
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-1 control-label">College</label>
          <div class="col-md-2">
            <%= @report.college_id ? @report.college.try(:name) : '---'%>
          </div>
    <label class="col-md-2 control-label">Department</label>
    <div class="col-md-3">
     <%= @report.department_id ? @report.department.try(:name) : '---'%>
    </div>
     <label class="col-md-1 control-label">Course</label>
    <div class="col-md-3">
      <%= @report.course_id ? @report.course.try(:name) : '---'%>
    </div>
          </div>
      </div>
  </div>

  <div class="form-group">
    
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Start</label>
        <div class="col-md-3">
          <%= @report.assessment_start_period %>  
        </div>
        <label class="col-md-2 control-label">End</label>
        <div class="col-md-3">
          <%= @report.assessment_end_period %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Learning Goals</label>
        <div class="col-md-3">
          <%= @report.unm_learning_goals %>  
        </div>
        <label class="col-md-2 control-label">Strategic Plan</label>
        <div class="col-md-3">
          <%= @report.unm_strategic_plan %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Measures</label>
        <div class="col-md-3">
          <%= @report.assessment_measures %>  
        </div>
        <label class="col-md-2 control-label">Benchmark</label>
        <div class="col-md-3">
          <%= @report.performance_benchmark %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Analysis</label>
        <div class="col-md-3">
          <%= @report.data_analysis %>  
        </div>
        <label class="col-md-2 control-label">Results</label>
        <div class="col-md-3">
          <%= @report.data_results %> 
        </div>
      </div>
    </div>
  </div>
 
  <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Student Learning Outcome</label>
        <div class="col-md-8">
          <%= @report.student_learning_utcomes %>  
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Recommendations</label>
        <div class="col-md-8">
          <%= @report.recommendations %>  
        </div>
      </div>
    </div>
  </div>
 
  <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Meeting Details</label>
        <div class="col-md-8">
          <%= @report.met_details %>  
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Status</label>
        <div class="col-md-8" style="font-weight:bolder;color:green">
          <%= @report.status %>  
        </div>
      </div>
    </div>
  </div>
 <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
  <% if @report.status == 'Completed' && user_role='Advisor' %>
          <td>
            <%= link_to 'Submit', submit_report_report_path(:id=>@report.id), data: { confirm: 'Are you sure want to submit to director?' }, :class=>'btn btn-primary btn-xs' %>
          </td>
        <% end %>
     </div>
      </div>
    </div>
</div>

 </center>